import os

TELEGRAM_TOKEN = os.getenv("TEL_BOT_TOKEN")
PROXY1_STRING = os.getenv("PROXY1_STRING")
PROXY2_STRING = os.getenv("PROXY2_STRING")
PROXY3_STRING = os.getenv("PROXY3_STRING")
PROXY4_STRING = os.getenv("PROXY4_STRING")
PROXY5_STRING = os.getenv("PROXY5_STRING")